# Generated by Django 4.2.5 on 2024-12-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="last_summarized",
            field=models.DateTimeField(
                blank=True, help_text="When the content was last summarized", null=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary of the content"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="summary_error",
            field=models.TextField(
                blank=True, help_text="Any errors encountered during summarization"
            ),
        ),
    ]
