# Generated by Django 4.2.5 on 2024-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
