# Generated by Django 4.2.5 on 2024-12-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_resource_last_summarized_resource_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="name_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
