# Generated by Django 4.2.5 on 2024-11-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_resource_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(max_length=255, upload_to="resources/"),
        ),
    ]
