# Generated by Django 4.2.5 on 2024-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_resource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="extraction_error",
            field=models.TextField(
                blank=True, help_text="Any errors encountered during text extraction"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="last_extracted",
            field=models.DateTimeField(
                blank=True, help_text="When the content was last extracted", null=True
            ),
        ),
    ]
