# Generated by Django 4.2.5 on 2024-11-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_resource_extraction_error_resource_last_extracted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="content_extracted",
            field=models.TextField(
                blank=True, help_text="Extracted text content from the file", null=True
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="extraction_error",
            field=models.TextField(
                blank=True,
                help_text="Any errors encountered during text extraction",
                null=True,
            ),
        ),
    ]
